apiVersion: v1
kind: PersistentVolume
metadata:
  name: kfk1-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  nfs:
    path: /np1openshift/np1-openshift-kafka/kfk2
    server: 10.7.102.64
  persistentVolumeReclaimPolicy: Retain